### ISSUE TITLE
[THOR] dashboard feedback: second round

### ISSUE THREAD

**Issue by daslerr** [daslerr/data-group#2]
Send month six version of metrics dashboard to focus group participants for final feedback after deliverable.

**Comment by suenjedt** [comment]
- need to get back to them with new dashboard. asking for feedback - with another google form?
- send them deliverable draft? or just the use cases? 
- thanks [and next steps?]

**Comment by suenjedt** [comment]
- structure them like RDA Service group use cases? [see Hylke's email for an example]

**Comment by daslerr** [comment]
request for feedback sent out March 4
